# Assignement 2


Please do not change, delete or edit any cells. Write your code in between designated lines.



## Question 1 (10 points)

In [1]:
# Can your print the letters of Agriculture by using for loops. Your output will look like this:
# A
# g
# r
# i
# c
# u
# l
# t
# u
# r
# e

## Your code here - down ##
for letter in "Agriculture":
  print(letter)
## Your code here - up ##


A
g
r
i
c
u
l
t
u
r
e


## Question 2 (40 Points)

In [2]:
# Find the sum of numbers from 1 to 50(including) by using for loops.

## Your code here - down ##
totalSum = 0
for num in range(1, 51):
  totalSum += num
print(totalSum)
## Your code here - up ##

1275


## Question 3 (50 points)

In [3]:
# Now let's find sum of even and odd numbers from 1 to 50 (including). Are the results same?

# Sum of even  numbers

## Your code here - down ##
evenSum = 0
for num in range(1, 51):
  if num % 2 == 0:
    evenSum += num
print(evenSum)
## Your code here - up ##

650


In [4]:
# Sum of odd numbers

## Your code here - down ##
oddNum = 0
for num in range(1, 51, 2):
  oddNum += num
print(oddNum)
## Your code here - up ##

625


In [5]:
# In this cell explain the difference.

# The sum of even noumbers from 1 to 50 (including) is 650, 
# The sum of odd numbers from 1 to 50 (including) is 625,
# They are not the same.

### In this cell explain the difference.

*   The sum of even noumbers from 1 to 50 (including) is 650, 
*   the sum of odd numbers from 1 to 50 (including) is 625,
*   They are not the same.

